# Generated by Django 5.2 on 2025-05-01 11:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_id_alter_user_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
