# Generated by Django 5.2 on 2025-05-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listed_items', '0001_initial'),
    ]

    operations = [
    ]
