# Generated by Django 5.2 on 2025-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listed_items', '0002_auto_20250506_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeditem',
            name='agent_id',
            field=models.UUIDField(null=True),
        ),
    ]
