# Generated by Django 5.2 on 2025-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrooms',
            name='user1',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='chatrooms',
            name='user2',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.UUIDField(),
        ),
    ]
