# Generated by Django 5.2 on 2025-05-02 05:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review_to', models.UUIDField(default=uuid.uuid4)),
                ('review_from', models.UUIDField(default=uuid.uuid4)),
                ('giver_image', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('review_text', models.TextField()),
            ],
        ),
    ]
